---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
spec:
  replicas: 3
    selector:
      matchLabels:
        app: podinfo-f
  template:
    spec:
      containers:
        - name: podinfo-f
          env:
            - name: PODINFO_UI_COLOR
              value: "#126ce5"
